# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [30]:
import numpy as np

## II. Numpy로 연산하기

### Vector와 Scala 간의 연산

In [31]:
x=np.array([1,2,3])
c=5

print("더하기 : {}".format(x+c))
print("빼기 : {}".format(x-c))
print("곱하기 : {}".format(x*c))
print("나누기 : {}".format(x/c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 간의 연산

In [32]:
y=np.array([1,3,5])
z=np.array([2,9,20])

print("더하기 : {}".format(y+z))
print("빼기 : {}".format(y-z))
print("곱하기 : {}".format(y*z))
print("나누기 : {}".format(y/z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array Indexing

In [33]:
w=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

w[1, 2]

7

### Array Slicing

In [34]:
w=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print(w[0:3, 1:3])
print(w[0:2])
print(w[0:2, :])

[[ 2  3]
 [ 6  7]
 [10 11]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


### Numpy의 Broadcasting

### 1. M by N, M by 1

In [35]:
M=np.array([[1,2,3],[4,5,6],[7,8,9]])
N=np.array([0,1,0])

N=N[:, None]

print(M+N)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


### 2. M by N, 1 by N

In [36]:
N=np.array([0,1,-1])

print(M*N)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


### 3. M by 1, 1 by N

In [37]:
M=np.array([1,2,3])
M=M[:, None]

N=np.array([2,0,-2])

print(M+N)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

### 영벡터

In [38]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### 일벡터

In [39]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### 대각행렬

In [40]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [41]:
np.diag((2,4,6))

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

### 항등행렬

In [42]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [43]:
np.eye(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 행렬곱

In [44]:
mat_1=np.array([[1,4],[2,3]])
mat_2=np.array([[7,9],[0,6]])

print(mat_1.dot(mat_2))
print(mat_1 @ mat_2)

[[ 7 33]
 [14 36]]
[[ 7 33]
 [14 36]]


### 트레이스

- Main Diagonal의 Sum
- `np.trace()`을 사용

In [45]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.trace()

15

In [47]:
np.eye(3, dtype=int).trace()

3

### 행렬식(determinant)
- 행렬을 대표하는 값 중 하나
- 선형변환 과정에서 Vector의 Scaling 척도
- `np.linalg.det()`으로 계산

In [48]:
arr_2=np.array([[2,3],[1,6]])

np.linalg.det(arr_2)

9.000000000000002

In [49]:
arr_3=np.array([[1,4,7],[2,5,8],[3,6,9]])

np.linalg.det(arr_3)

0.0

### 역행렬

- 행렬 A에 대해서 AB = BA = I를 만족하는 행렬 B
- `np.linalg.inv()`을 사용

In [50]:
mat=np.array([[1,4],[2,3]])
print(mat)
mat_inv=np.linalg.inv(mat)
print(mat_inv)

print(mat@mat_inv)

[[1 4]
 [2 3]]
[[-0.6  0.8]
 [ 0.4 -0.2]]
[[1. 0.]
 [0. 1.]]


### 고유값과 고유벡터

- 정방행렬(nxn) A에 대해서 $Ax = \lambda x$을 만족하는 $\lambda$와 x를 각각 고유값과 고유벡터라 한다. 
- `np.linalg.eig()`로 계산

In [51]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [52]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

In [53]:
eig_val, eig_vec=np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [54]:
mat @ eig_vec[:, 0]

array([0., 1., 0.])

In [55]:
eig_val[0] * eig_vec[:, 0] #브로드캐스팅 곱

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [56]:
def get_L2_norm(arr):
    ret=0
    for i in arr:
        ret+=i
    return ret**(1/2)

print(get_L2_norm([2,4,7]))

3.605551275463989


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [57]:
def is_singular(arr):
    if np.linalg.det(arr):
        return False
    return True

print(is_singular([[1,2],[2,4]]))
print(is_singular([[1,2],[2,5]]))

True
False
