In [1]:
import numpy as np

In [4]:
a1=np.array([3,4,5,6,7])
print(a1)
print(a1[0],a1[1],a1[2],a1[3],a1[4])

print(a1.shape)

[3 4 5 6 7]
3 4 5 6 7
(5,)


In [6]:
a2=np.array([ [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]] ])
print(a2.shape)

(3, 3, 3)


In [13]:
print(np.zeros(10))
print(np.ones(10))
print(np.ones((3,3,3)))
print(np.full((2,3), 1.23))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[1.23 1.23 1.23]
 [1.23 1.23 1.23]]


In [15]:
#단위행렬
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
#삼각행렬
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [19]:
#empty는 초기화하지 않음
#빠르게 배열 생성 but 해당 메모리에 있던 값 포함 가능
a1=np.empty(10)
a1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
print(np.zeros_like(a1))
print(np.ones_like(a1))
print(np.full_like(a1,3))
print(np.empty_like(a1))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [35]:
print(np.arange(0,30,5)) #range처럼 단위 기준으로 증가
print(np.linspace(0,30,5)) #단위 기준으로 간격 생성
print(np.logspace(0.1, 1, 20)) #log값으로 반환

[ 0  5 10 15 20 25]
[ 0.   7.5 15.  22.5 30. ]
[ 1.25892541  1.40400425  1.565802    1.74624535  1.94748304  2.1719114
  2.42220294  2.70133812  3.0126409   3.35981829  3.74700446  4.17881006
  4.66037703  5.19743987  5.79639395  6.46437163  7.2093272   8.04013161
  8.9666781  10.        ]


In [47]:
print(np.random.random((3, 3)))
print(np.random.randint(0,10, (2,3))) #(값의 범위,(dimension))
print(np.random.normal(0, 1, (3, 3))) #정규분포를 따름
print(np.random.rand(3,3))

[[0.57982203 0.62139542 0.37946229]
 [0.8848322  0.41112043 0.39045082]
 [0.03138566 0.98704934 0.17407168]]
[[4 2 4]
 [7 6 7]]
[[-0.88273173  0.34783047  0.85485865]
 [ 0.12669308 -0.68527322  0.23803201]
 [-0.52444942 -0.74952731 -0.21878323]]
[[0.34985722 0.16844554 0.46095958]
 [0.89573797 0.31863148 0.48552382]
 [0.46725717 0.89762996 0.6827665 ]]


In [57]:
print(np.zeros(20, dtype=int))
print(np.zeros((3, 3), dtype=int))
print(np.zeros((3, 3), dtype=bool))
print(np.zeros((3, 3), dtype=float))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[False False False]
 [False False False]
 [False False False]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [58]:
#날짜
date=np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [59]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [62]:
datetime = np.datetime64('2020-06-01 12:00:12.34','ms')
datetime

numpy.datetime64('2020-06-01T12:00:12.340')

In [63]:
#배열 속성
def array_info(array):
    print(array)
    print("ndim:", array.ndim)
    print("shape:", array.shape)
    print("dtype:", array.dtype)
    print("size:", array.size)
    print("itemsize:", array.itemsize)
    print("nbytes:", array.nbytes)
    print("strides:", array.strides)

array_info(a1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
ndim: 1
shape: (10,)
dtype: float64
size: 10
itemsize: 8
nbytes: 80
strides: (8,)
